---
title: "Summary Tables"
author: "ArdiMirzaei"
date: "`r format(Sys.time(), '%d %b %Y')`"
output: officedown::rdocx_document
---

```{r setup, echo =FALSE, results = 'asis', message = FALSE, warning = FALSE}
library(dplyr)
library(flextable)

```
# Tables for Top 5 and Bottom 5. 

Tables are filtered for Atom as the phosphate only. 

## Top 5 

```{r top5,echo=FALSE,  message = FALSE, warning = FALSE}

ft <- df %>%
  mutate(nl =   apply(df[c("n.1.", "n.2.", "n.3.", "n.4.")], 1, paste,collapse="")) %>%
  filter(alphavalue < 3.5) %>%
  filter(ATOM == 'P') %>%
  group_by(drug, compound, alphavalue) %>%
  arrange(RMSD_MAP) %>%
  mutate(Rank = min_rank(RMSD_MAP)) %>%
  # slice(1:5) %>%
  filter(Rank <=5 | nl == '6666' | nl == '6677') %>%
  ungroup() %>%
  select( drug, compound, nl, RMSD_MAP, Rank) %>%
  mutate(compound = as.numeric(gsub("Compound_","",compound))) %>%
  group_by(drug, compound) %>%
  arrange(drug, compound) %>%
  ungroup() %>%
  rename(
    `Chemical Group`  = drug,
    `Compound` = compound,
    `n_l` = nl
         ) %>%
  flextable() %>%
  theme_box() %>%  
  merge_v(j = c('Chemical Group', 'Compound')) %>%
   mk_par(j = 3, part = "header", value = as_paragraph(as_i("n"), as_sub("(l)")))  

ft <- set_caption(ft, caption = "Top 5 scoring RMSD MAP ")
ft <- autofit(ft) # fit_to_width(ft, max_width = 15) # autofit(ft)

# color_ind <- which(d == "Red", arr.ind = TRUE)


ft
```

## Bottom 5 

```{r bottom5,echo=FALSE,  message = FALSE, warning = FALSE}

ft <- df %>%
  mutate(nl =   apply(df[c("n.1.", "n.2.", "n.3.", "n.4.")], 1, paste,collapse="")) %>%
  filter(alphavalue < 3.5) %>%
  filter(ATOM == 'P') %>%
  group_by(drug, compound, alphavalue) %>%
  arrange(RMSD_MAP) %>%
  slice((n()-5):n()) %>%
  select(drug, compound, alphavalue, nl, RMSD_MAP) %>%
  flextable() %>%
  theme_box() %>%  
  merge_v(j = c('drug', 'compound', 'alphavalue'))

ft <- set_caption(ft, caption = "Bottom 5 scoring RMSD MAP ")
ft <- autofit(ft) # fit_to_width(ft, max_width = 15) # autofit(ft)
ft
```